spring:
  profiles:
    default: local  # 기본적으로 활성화할 프로파일을 local 로 설정

---
spring:
  config:
    activate:
      import: optional:file:.env[.properties]
      on-profile: local
  # 로컬 환경 설정
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
openapi:
  key: ${OPEN_API_KEY}
kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: http://localhost:8080/auth/kakao-oauth
Jwt:
  secret: ${JWT_SECRET_KEY}
  token:
    access-expiration-time: 360000 # Milliseconds for 1 hour
    refresh-expiration-time: 259200000 # Milliseconds for 30 days

---
spring:
  config:
    activate:
      on-profile: prod
  # 프로덕션 환경 설정
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
Jwt:
  secret: ${JWT_SECRET_KEY}
  token:
    access-expiration-time: 360000 # Milliseconds for 1 hour
    refresh-expiration-time: 259200000 # Milliseconds for 30 days

openapi:
  key: ${OPEN_API_KEY}

kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: http://localhost:8080/auth/kakao-oauth